### ISSUE TITLE
combining isEmpty with many causes an internal error

### ISSUE THREAD

**Issue by jappeace** [GaloisInc/cereal#105]
```haskell
testIsEmpty :: IO ()
testIsEmpty = do
  assertEqual "is empty (works)" (Right True) (runGet isEmpty mempty)
  assertEqual "is empty many (don't work)" (Right [True]) (runGet (many isEmpty) mempty)
```

The is empty many results in this:

```
 see if empty is empty:             unit: internal error: Unable to commit 1048576 bytes of memory
    (GHC version 9.0.2 for x86_64_unknown_linux)
    Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
Aborted (core dumped)
```

I'm on cereal-0.5.8.2

**Comment by elliottt** [comment]
I'm not sure this is a bug, as `isEmpty` won't actually consume any data, and will always succeed. The result will be that `many isEmpty` with an empty input will build an infinite list of `True` values, and as you're observing eventually run out of memory.

**Comment by jappeace** [comment]
I guess this makes sense, although it's a little ironic.
