### ISSUE TITLE
Get takes twice as long as put for lists

### ISSUE THREAD

**Issue by mhwombat** [GaloisInc/cereal#23]
I may be missing something, but I would expect `get` to be _faster_ than `put`. But it takes twice as long. Here's a simple test:

    import Data.Serialize
    
    main :: IO ()
    main = do
      let x = encode ([1..1000000] :: [Double])
      (decode x :: Either String [Double]) `seq` return ()

And here's the profile (scroll down to encode/decode, then scroll right):

    	Wed Apr  9 13:09 2014 Time and Allocation Profiling Report  (Final)
    
    	   realtra-benchmark2 +RTS -p -RTS
    
    	total time  =       28.11 secs   (28105 ticks @ 1000 us, 1 processor)
    	total alloc = 11,402,369,328 bytes  (excludes profiling overheads)
    
    COST CENTRE  MODULE                 %time %alloc
    
    >>=.\.ks'    Data.Serialize.Get      25.4   20.1
    >>=.\        Data.Serialize.Get      15.8    9.9
    put          Data.Serialize           9.6   12.8
    roll.unstep  Data.Serialize           6.1   11.9
    unroll.step  Data.Serialize           5.2   11.3
    >>=          Data.Serialize.Get       3.9    0.0
    withSize.\   Data.Serialize.Builder   3.2    3.4
    return.\     Data.Serialize.Get       3.0    0.0
    put          Data.Serialize           3.0    2.5
    >>           Data.Serialize.Put       2.7    3.2
    fmap.\.ks'   Data.Serialize.Get       2.5    8.8
    getListOf.go Data.Serialize.Get       2.3    4.6
    put          Data.Serialize           2.2    2.0
    return       Data.Serialize.Get       2.1    0.0
    unroll       Data.Serialize           1.9    3.4
    fmap.\       Data.Serialize.Get       1.7    1.3
    getWord8     Data.Serialize.Get       1.3    0.0
    getListOf    Data.Serialize.Get       1.3    0.0
    put          Data.Serialize           1.1    1.3
    main.x       Main                     0.5    1.5
    
    
                                                                        individual     inherited
    COST CENTRE              MODULE                   no.     entries  %time %alloc   %time %alloc
    
    MAIN                     MAIN                      53           0    0.0    0.0   100.0  100.0
     CAF                     Main                     105           0    0.0    0.0   100.0  100.0
      main                   Main                     106           1    0.0    0.0   100.0  100.0
       main.x                Main                     117           1    0.5    1.5    32.4   43.3
        encode               Data.Serialize           118           1    0.0    0.0    31.9   41.8
         sndS                Data.Serialize.Put       126           1    0.0    0.0     0.0    0.0
         put                 Data.Serialize           125           1    6.1    8.6    21.2   31.2
          put                Data.Serialize           137     1000000    0.6    1.0    15.0   22.6
           put               Data.Serialize           138     1000000    2.2    1.6    14.4   21.6
            put              Data.Serialize           184     1000000    0.2    0.4     0.6    1.1
             put             Data.Serialize           185     1000000    0.4    0.7     0.4    0.7
            >>.(...)         Data.Serialize.Put       161     1000000    0.1    0.0     0.1    0.0
             unPut           Data.Serialize.Put       162     1000000    0.0    0.0     0.0    0.0
            >>.w'            Data.Serialize.Put       160     1000000    0.1    0.0     0.1    0.0
            mappend          Data.Serialize.Builder   150     1000000    0.0    0.0     0.0    0.0
            put.hi           Data.Serialize           148     1000000    0.0    0.0     0.0    0.0
            put              Data.Serialize           147     1000000    1.4    1.4    10.2   17.6
             unroll          Data.Serialize           177           0    1.9    3.4     7.1   14.7
              unroll.step    Data.Serialize           178     8000000    5.2   11.3     5.2   11.3
             put.sign        Data.Serialize           172     1000000    0.3    0.1     0.3    0.1
             >>              Data.Serialize.Put       163     1000000    1.1    1.3     1.4    1.3
              >>.(...)       Data.Serialize.Put       174     1000000    0.1    0.0     0.1    0.0
               unPut         Data.Serialize.Put       175     1000000    0.0    0.0     0.0    0.0
              >>.w'          Data.Serialize.Put       173     1000000    0.1    0.0     0.1    0.0
              >>.w           Data.Serialize.Put       170     1000000    0.0    0.0     0.0    0.0
              >>.(...)       Data.Serialize.Put       167     1000000    0.1    0.0     0.1    0.0
               unPut         Data.Serialize.Put       168     1000000    0.0    0.0     0.0    0.0
              mappend        Data.Serialize.Builder   164     1000000    0.0    0.0     0.0    0.0
            put.lo           Data.Serialize           146     1000000    0.0    0.0     0.0    0.0
            >>               Data.Serialize.Put       139     2000000    0.9    1.3     1.2    1.3
             >>.(...)        Data.Serialize.Put       182     1000000    0.1    0.0     0.1    0.0
              unPut          Data.Serialize.Put       183     1000000    0.0    0.0     0.0    0.0
             >>.w'           Data.Serialize.Put       181     1000000    0.1    0.0     0.1    0.0
             >>.w            Data.Serialize.Put       149     1000000    0.0    0.0     0.0    0.0
             >>.(...)        Data.Serialize.Put       144     1000000    0.1    0.0     0.1    0.0
              unPut          Data.Serialize.Put       145     1000000    0.0    0.0     0.0    0.0
             mappend         Data.Serialize.Builder   140     1000000    0.0    0.0     0.0    0.0
          sndS               Data.Serialize.Put       130     9000001    0.1    0.0     0.1    0.0
          unPut              Data.Serialize.Put       129     9000001    0.0    0.0     0.0    0.0
          mappend            Data.Serialize.Builder   127     1000001    0.0    0.0     0.0    0.0
         unPut               Data.Serialize.Put       124           1    0.0    0.0     0.0    0.0
         toByteString        Data.Serialize.Builder   119           1    0.1    0.2    10.7   10.7
          flush.\            Data.Serialize.Builder   200           1    0.0    0.0     0.0    0.0
          put                Data.Serialize           128           0    3.5    4.2    10.6   10.5
           put               Data.Serialize           141           0    0.0    0.0     1.7    1.4
            put              Data.Serialize           142           0    0.5    0.4     1.7    1.4
             put             Data.Serialize           187           0    0.0    0.0     0.3    0.2
              put            Data.Serialize           188           0    0.3    0.2     0.3    0.2
             put             Data.Serialize           165           0    0.2    0.2     0.5    0.5
              >>             Data.Serialize.Put       166           0    0.3    0.3     0.3    0.3
             >>              Data.Serialize.Put       143           0    0.4    0.3     0.4    0.3
           withSize          Data.Serialize.Builder   133           0    0.9    0.0     5.4    4.9
            withSize.\       Data.Serialize.Builder   134    11000001    3.2    3.4     4.5    4.9
             flush.\         Data.Serialize.Builder   192         763    0.0    0.2     0.0    0.2
              put            Data.Serialize           193           0    0.0    0.0     0.0    0.0
               put           Data.Serialize           194           0    0.0    0.0     0.0    0.0
                put          Data.Serialize           197           0    0.0    0.0     0.0    0.0
                put          Data.Serialize           195           0    0.0    0.0     0.0    0.0
                 put         Data.Serialize           196           0    0.0    0.0     0.0    0.0
             put             Data.Serialize           157           0    0.0    0.0     1.3    1.3
              put            Data.Serialize           158           0    0.3    0.4     1.3    1.3
               put           Data.Serialize           189           0    0.0    0.0     0.4    0.4
                put          Data.Serialize           190           0    0.4    0.4     0.4    0.4
               put           Data.Serialize           159           0    0.6    0.4     0.6    0.4
             runBuilder      Data.Serialize.Builder   135    11000001    0.0    0.0     0.0    0.0
          runBuilder         Data.Serialize.Builder   123           1    0.0    0.0     0.0    0.0
       decode                Data.Serialize           107           1    0.0    0.0    67.6   56.7
        get                  Data.Serialize           109           1    0.0    0.0    67.6   56.7
         getListOf           Data.Serialize.Get       110           1    1.3    0.0    67.6   56.7
          getListOf.go       Data.Serialize.Get       229     8000000    1.3    4.3     1.3    4.3
           return            Data.Serialize.Get       231     1000000    0.0    0.0     0.0    0.0
           >>=               Data.Serialize.Get       230     7000000    0.0    0.0     0.0    0.0
          >>=                Data.Serialize.Get       111    14000002    3.9    0.0    65.1   52.4
           >>=.\             Data.Serialize.Get       112    49000004   15.8    9.9    61.2   52.4
            get              Data.Serialize           242           0    0.1    0.0     0.1    0.0
            get              Data.Serialize           239           0    0.1    0.0     0.1    0.0
            getWord8         Data.Serialize.Get       216           0    1.3    0.0     2.9    1.3
             fmap            Data.Serialize.Get       218           0    0.5    0.0     1.6    1.3
              fmap.\         Data.Serialize.Get       219     9000000    1.1    1.3     1.1    1.3
               unGet         Data.Serialize.Get       220     9000000    0.0    0.0     0.0    0.0
            get              Data.Serialize           212           0    0.1    0.0     0.1    0.0
            get              Data.Serialize           209           0    0.1    0.0     0.1    0.0
            >>=.\.ks'        Data.Serialize.Get       201    49000004   25.4   20.1    41.9   41.3
             get.v           Data.Serialize           234     1000000    0.9    0.0     7.1   11.9
              roll.unstep    Data.Serialize           236     7000000    6.1   11.9     6.1   11.9
             get             Data.Serialize           225           0    0.1    0.0     0.1    0.0
             getListOf.go    Data.Serialize.Get       206     1000001    1.0    0.4     1.3    0.4
              return         Data.Serialize.Get       232           1    0.1    0.0     0.3    0.0
               return.\      Data.Serialize.Get       233     1000001    0.1    0.0     0.1    0.0
                finalK       Data.Serialize.Get       244           1    0.0    0.0     0.0    0.0
             shiftl_w64      Data.Serialize.Get       205    14000007    0.1    0.0     0.1    0.0
             return          Data.Serialize.Get       203    26000002    2.0    0.0     7.9    8.8
              return.\       Data.Serialize.Get       204    26000002    2.9    0.0     5.9    8.8
               getWord8      Data.Serialize.Get       221           0    0.0    0.0     3.1    8.8
                fmap         Data.Serialize.Get       222           0    0.0    0.0     3.1    8.8
                 fmap.\      Data.Serialize.Get       223           0    0.6    0.0     3.1    8.8
                  fmap.\.ks' Data.Serialize.Get       224     9000000    2.5    8.8     2.5    8.8
             unGet           Data.Serialize.Get       202    49000004    0.0    0.0     0.0    0.0
            getWord64be      Data.Serialize.Get       116           0    0.3    0.0     0.3    0.0
            unGet            Data.Serialize.Get       113    49000004    0.0    0.0     0.0    0.0
        unGet                Data.Serialize.Get       108           1    0.0    0.0     0.0    0.0
     CAF                     Data.Serialize           104           0    0.0    0.0     0.0    0.0
      get                    Data.Serialize           243           1    0.0    0.0     0.0    0.0
      get                    Data.Serialize           240           1    0.0    0.0     0.0    0.0
       >>=                   Data.Serialize.Get       241           1    0.0    0.0     0.0    0.0
      get                    Data.Serialize           237           1    0.0    0.0     0.0    0.0
       >>=                   Data.Serialize.Get       238           1    0.0    0.0     0.0    0.0
      roll                   Data.Serialize           235           1    0.0    0.0     0.0    0.0
      get                    Data.Serialize           213           1    0.0    0.0     0.0    0.0
      get                    Data.Serialize           210           1    0.0    0.0     0.0    0.0
       get                   Data.Serialize           226           1    0.0    0.0     0.0    0.0
        getListOf            Data.Serialize.Get       227           1    0.0    0.0     0.0    0.0
         >>=                 Data.Serialize.Get       228           1    0.0    0.0     0.0    0.0
       >>=                   Data.Serialize.Get       211           2    0.0    0.0     0.0    0.0
      get                    Data.Serialize           207           1    0.0    0.0     0.0    0.0
       >>=                   Data.Serialize.Get       208           1    0.0    0.0     0.0    0.0
      put                    Data.Serialize           186           1    0.0    0.0     0.0    0.0
      unroll                 Data.Serialize           176           1    0.0    0.0     0.0    0.0
      put                    Data.Serialize           169           1    0.0    0.0     0.0    0.0
      put                    Data.Serialize           151           0    0.0    0.0     0.0    0.0
       withSize              Data.Serialize.Builder   156           1    0.0    0.0     0.0    0.0
       >>                    Data.Serialize.Put       152           0    0.0    0.0     0.0    0.0
        >>.w                 Data.Serialize.Put       155           1    0.0    0.0     0.0    0.0
        >>.(...)             Data.Serialize.Put       154           1    0.0    0.0     0.0    0.0
        unPut                Data.Serialize.Put       153           1    0.0    0.0     0.0    0.0
      put                    Data.Serialize           131           1    0.0    0.0     0.0    0.0
       mempty                Data.Serialize.Builder   198           1    0.0    0.0     0.0    0.0
       mappend               Data.Serialize.Builder   136           1    0.0    0.0     0.0    0.0
       withSize              Data.Serialize.Builder   132           1    0.0    0.0     0.0    0.0
     CAF                     Data.Serialize.Put       103           0    0.0    0.0     0.0    0.0
      mempty                 Data.Serialize.Builder   180           1    0.0    0.0     0.0    0.0
      mappend                Data.Serialize.Builder   179           1    0.0    0.0     0.0    0.0
      withSize               Data.Serialize.Builder   171           2    0.0    0.0     0.0    0.0
     CAF                     Data.Serialize.Get       102           0    0.0    0.0     0.0    0.0
      getWord8               Data.Serialize.Get       214           1    0.0    0.0     0.0    0.0
       fmap                  Data.Serialize.Get       217           1    0.0    0.0     0.0    0.0
       >>=                   Data.Serialize.Get       215           2    0.0    0.0     0.0    0.0
      getWord64be            Data.Serialize.Get       114           1    0.0    0.0     0.0    0.0
       >>=                   Data.Serialize.Get       115           2    0.0    0.0     0.0    0.0
     CAF                     Data.Serialize.Builder   101           0    0.0    0.0     0.0    0.0
      flush                  Data.Serialize.Builder   191           1    0.0    0.0     0.0    0.0
      defaultSize            Data.Serialize.Builder   120           1    0.0    0.0     0.0    0.0
       defaultSize.overhead  Data.Serialize.Builder   122           1    0.0    0.0     0.0    0.0
       defaultSize.k         Data.Serialize.Builder   121           1    0.0    0.0     0.0    0.0
     CAF                     GHC.Conc.Signal           93           0    0.0    0.0     0.0    0.0
     CAF                     GHC.IO.Handle.FD          83           0    0.0    0.0     0.0    0.0
     CAF                     GHC.IO.Encoding           78           0    0.0    0.0     0.0    0.0
     CAF                     GHC.IO.Encoding.Iconv     69           0    0.0    0.0     0.0    0.0

**Comment by elliottt** [comment]
Sorry I've taken so long to get back to you, but I'm not so surprised by this.  I'm afraid I don't have any good insight here, other than Get does error checking, while Put just renders out data.  If you've found a way in the meantime to further speed up Get, I'd be happy to integrate the changes :)
