### ISSUE TITLE
`decode` crashes with bad character sets

### ISSUE THREAD

**Issue by jprider63** [GaloisInc/cereal#27]
When I attempt to decode a bytestring that contains bad character sets, the program crashes with the following error: 

    Prelude.chr: bad argument: 3077277

Would it make sense for `decode` to catch this error and return Left "Invalid character set", if this happens?

**Comment by elliottt** [comment]
If there's a way to validate the input to `chr` before calling it, I would be happy to add that functionality.  I'd like to avoid catching the exception that `chr` raises, as that would necessitate putting the `decode` function into `IO`.

The way that I would parse a string with a possibly bad charset is to instead use the `getByteString` function, and a package like text to do the actual decoding.  This way, you get a little more control, and avoid the use of `chr` in the `Serialize` instance.

**Comment by jprider63** [comment]
It looks like the source code for `chr` is [here](http://hackage.haskell.org/package/base-4.7.0.2/docs/src/GHC-Char.html#chr). I think it'd be simple to wrap this function to validate the inputs, so that it returns a `Maybe` or `Either`. How does that sound?

**Comment by elliottt** [comment]
I'll do a bug-fix release today, can we consider this issue closed?

**Comment by jprider63** [comment]
Sounds good to me! Thanks!
