### ISSUE TITLE
Add HashMap instance

### ISSUE THREAD

**Issue by treeowl** [GaloisInc/cereal#30]
`Data.HashMap.Map` is an instance of `Data`, so this *should* be easy.

**Comment by elliottt** [comment]
Which package are you referring to?  The one from the `hashmap` package indicates that it's been deprecated in favor of `unordered-containers`.

**Comment by treeowl** [comment]
Sorry, I got lost in nested deprecations. I mean `Data.HashMap.Base.HashMap` in `unordered-containers`.

**Comment by elliottt** [comment]
I'd rather not add instances for libraries that aren't used by `cereal` directly, as that just complicates the build for people that don't depend on them.  Would it be sufficient to make a newtype for `HashMap`, giving its `Serialize` implementation as `get` with `fromList`, and `put` with `toList`?  That way, you would have control over how the data was serialized, and `cereal` could avoid an `unordered-containers` dependency.

**Comment by treeowl** [comment]
I suppose that would do.
