### ISSUE TITLE
`time` package, StdGen instances...any reason they are not offered?

### ISSUE THREAD

**Issue by mstksg** [GaloisInc/cereal#32]
Hi,

I'm just wondering if there was any particular reason why instances of `UTCTime`/`Day` etc. from the _time_ package, and `StdGen` from the _random_ package are missing...these packages are both considered pretty stable and central to the haskell ecosystem; is there a reason other than minimizing dependencies?

**Comment by elliottt** [comment]
Minimizing dependencies :)

I like to avoid dependencies when possible, as the original need for cereal arose from a use in [HaLVM](http://github.com/galoisinc/halvm), which isn't able to build everything on hackage.

**Comment by mstksg** [comment]
fair enough :)  The main reason I ask is because I have a library that extensively uses *cereal*'s interface, but most for applications my users end up having to manually define instances.  do you know if anyone else has had a similar issue...and if so, how they have addressed it?

if this really is the best way, though, it's perfectly understandable and good.  thanks so much for the great library :)

**Comment by elliottt** [comment]
As cereal provides default implementations for `get` and `put` in the `Serialize` class in terms of GHC Generics, you should just be able to write:

```haskell
{-# LANGUAGE DeriveGeneric #-}
import GHC.Generics (Generic)
data Foo = Foo ... deriving (Generic)
instance Serialize Foo
```

Even with this approach you would still end up with orphan instances for the data types in `time`, so I'm not sure if this fully addresses your question.  Maybe as `time` comes bundled with GHC, and builds on the HaLVM, I should just add the dependency and instances.
