### ISSUE TITLE
Parse results are inconsistent between lazy-bytestring and eager-bytestring

### ISSUE THREAD

**Issue by khibino** [GaloisInc/cereal#36]
This is example code of inconsistency in cereal-0.4.1.1 with bytestring-0.10.4.0.

Bytestrings are concatinated from the same bytestring-chunk list.

```haskell
import Control.Applicative
import Data.Word
import qualified Data.ByteString as BS
import qualified Data.ByteString.Lazy as LB
import Data.Serialize.Get

data Bug =
  Bug Word8 [(Word8, Word8)]
  deriving (Eq, Show)

chunks :: [BS.ByteString]
chunks = [BS.pack [0, 1], BS.pack [2], BS.pack [3], BS.pack [4]]

getPs :: Get [(Word8, Word8)]
getPs = do
  e <- isEmpty
  if e
    then    return []
    else do f  <- getWord8
            s  <- getWord8
            tl <- getPs
            return $ (f, s) : tl

getBug :: Get Bug
getBug = Bug <$> getWord8 <*> getPs

lazy :: [BS.ByteString] -> Either String Bug
lazy =
  runGetLazy
  getBug
  . LB.fromChunks

eager :: [BS.ByteString] -> Either String Bug
eager =
  runGet
  getBug
  . BS.concat

expect :: Bool
expect = lazy chunks == eager chunks

main :: IO ()
main = do
  print   expect
  print $ lazy  chunks
  print $ eager chunks
```

Execution output is as follows.

```
False
Right (Bug 0 [(1,2)])
Right (Bug 0 [(1,2),(3,4)])
```

I think the same result is expected in this case, isn't it?

**Comment by elliottt** [comment]
I think this is actually because of the way that `isEmpty` interacts with runGetLazy.  As runGetLazy treats the input as a sequence of calls to runGetPartial, incrementally parsing each chunk, `isEmpty` is unable to tell if it's at the end of the whole input, and can only report if you're near the end of the current chunk.  As a result, your `getPs` function will return early in the lazy case.  This is why the instance of `Serialize` for lists always puts a length before starting to write out elements.

**Comment by khibino** [comment]
Cases using cereal-0.3.5.2 or cereal-0.4.0.1, outputs are as follows.

```
True
Right (Bug 0 [(1,2),(3,4)])
Right (Bug 0 [(1,2),(3,4)])
```
`isEmpty` with `runGetLazy` had worked well in older versions.
The creal-0.4.1.1 change this behavior.

Will the rest length management become essential to detect the end of a lazy stream in future versions?

**Comment by elliottt** [comment]
Well, I'm not sure how it was working on those previous versions of the library, but I've pushed a fix to master that should address your problem. Can you test with master and make sure that your bug is resolved?

Thanks for the bug report!

**Comment by khibino** [comment]
I have tested my parser with new code. Fixed behavior looks good! Thanks.
