### ISSUE TITLE
GHC Generics instance deriving broken

### ISSUE THREAD

**Issue by ozgurakgun** [GaloisInc/cereal#43]
This commit seems to have removed the code to define the "GENERICS". But the code still contains ifdefs on it.

(Edit, forgot to link to the commit: b18e6afbbf66b4418dc8b0ac76eaa0e5e6d0110c)

I am not sure how any code relying on this machinery works at the moment -- they cannot as far as I can see.

Fix should be either to define GENERICS somewhere else or remove the ifdefs altogether.

**Comment by elliottt** [comment]
Ah, some overzealous refactoring of the cabal file on my part. I'll push a
fix today :)

**Comment by ozgurakgun** [comment]
Thanks for the quick fix!
