### ISSUE TITLE
Quadratic behavior of `demandInput`

### ISSUE THREAD

**Issue by bitonic** [GaloisInc/cereal#48]
And probably other functions, given the large number of `B.append`s in `Data.Serialize.Get`.

The practical consequence is that deserializing using many chunks is quadratic in the number of chunks.

See https://github.com/kolmodin/binary/pull/76 for a related problem in `binary`.

**Comment by elliottt** [comment]
Thanks for all the recent interest in cereal!

Are you interested in making similar changes to what you did for binary? If not, I can probably retrofit what you've done, but would be happy to look over patches if you've already got an idea of what needs to change :)

**Comment by bitonic** [comment]
I have this code I wrote earlier but it's currently failing some tests and I hadn't have the time to debug it:

```
-- | If at least @n@ bytes of input are available, return the current
--   input, otherwise fail.
ensureRec :: Int -> Get B.ByteString
ensureRec remaining00 = go remaining00 []
  where
    go !remaining0 bss0 = Get $ \s0 b0 m0 kf ks -> let
        tooFewBytes = kf s0 b0 m0 ["demandInput"] "too few bytes"
        remaining = remaining0 - B.length s0
        bss = s0 : bss0
        b1 = extendBuffer b0 s0
        in if remaining <= 0
            then let
                s = B.concat (reverse bss)
                in ks s b1 m0 s
            else case m0 of
                Complete -> tooFewBytes
                Incomplete mb -> Partial $ \s ->
                    if B.null s
                    then tooFewBytes
                    else let
                        mb' = case mb of
                            Just l -> Just $! l - B.length s
                            Nothing -> Nothing 
                        in unGet (go remaining bss) s b1 (Incomplete mb') kf ks
```

I'm pretty sure it's because of mishandling of the `Buffer` argument.

I'll probably have time to fix it myself this week, but if you want to step in, that works too.

**Comment by bitonic** [comment]
Pull request #50 fixes this.
