### ISSUE TITLE
`runGetChunk` use case?

### ISSUE THREAD

**Issue by winterland1989** [GaloisInc/cereal#58]
Recently I'm hacking into cereal codebase to build a `takeTill`, but i don't quite get why `runGetChunk` and `data More = Complete | Incomplete (Maybe Int)` existed. it seems `runGetPartial` just do fine without provide any remaining estimate, and `More` field force me to calculate remaining estimate every chunk. So the quesiton is, what's the use case of `runGetChunk`?

**Comment by winterland1989** [comment]
The same quetion goes to `Buffer` as well, since all `run...` functions provide `Nothing` as `Buffer`, why do we keep it in the codebase at all?

**Comment by elliottt** [comment]
There's a good chance that it exists because the API has evolved over time.

The `Buffer` type is used to keep track of chunks read across choice points. Without it, backtracking across a chunk read will request a new chunk.

**Comment by elliottt** [comment]
Now I remember, the `Incomplete` tag is for when the action is being run from `runGetPartial`, and explicitly run as something that may expect another chunk. The `Maybe Int` field of the constructor indicates whether or not you know the length of the whole input. So, if you were streaming from a network connection, each chunk you passed in would be given `Incomplete Nothing` as the input, but if you were streaming from a file, you could pass `Incomplete (Just size)`.

**Comment by winterland1989** [comment]
I see, i don't even know cereal support backtrace before ; ), Thanks!
