### ISSUE TITLE
Explicit Int Putters

### ISSUE THREAD

**Issue by andrewthad** [GaloisInc/cereal#60]
In [Data.Serialize.Put](http://hackage.haskell.org/package/cereal-0.5.3.0/docs/Data-Serialize-Put.html), there are a number of functions for putting `Word`, `Word64`, etc, but the equivalent functions for working on `Int`s are missing. Would you take a PR adding these?

**Comment by elliottt** [comment]
Absolutely!

**Comment by andrewthad** [comment]
PR is up.
