### ISSUE TITLE
How about making use of attoparsec's approach to parsing (buffer with cursor)?

### ISSUE THREAD

**Issue by SX91** [GaloisInc/cereal#64]
I've done some porting of attoparsec's `Parser` to `Get`: https://github.com/SX91/cereal/tree/buffer-pos. Please, take a look. Performance is almost the same though, at least with included benchs.
Overlaps with https://github.com/GaloisInc/cereal/pull/62.

PS: I've taken `Buffer` module from Attoparsec package and modified it a bit. Probably need to add some copyrights.

**Comment by SX91** [comment]
If you're interested, I'd make a PR and work on this some more until it gets merged.

**Comment by elliottt** [comment]
If you can show a dramatic performance improvement I'd be interested, but if it's fairly similar it doesn't seem worth the change.

Looking over your branch, it's hard to tell how your changes handle backtracking with an incremental parser. If backtracking occurs across a request for another chunk, does that chunk get cached in the buffer?

**Comment by SX91** [comment]
`prompt` appends buffer with new data every time a new chunk is provided. Almost every function (except `isolate`, because there wouldn't be any appends) uses new buffer in continuations.
https://github.com/SX91/cereal/blob/buffer-pos/src/Data/Serialize/Get.hs#L407

There should be some performance improvements with isolate, lookahead etc. But bench doesn't cover them. I've tested it with `weigh` on some of my input and it seems new code generates slightly more bytes. Maybe I need to add some strictness somewhere to eliminate some unneccesary thunks.

Well, all that's changed is now it's one big buffer with current position. You can move anywhere within this buffer, forward, backward, etc, without modifying that buffer at all. Buffer itself gets modified in `ensureX` functions (appends a new chunk).

**Comment by elliottt** [comment]
If it simplified the management of the buffered chunks, that would be a win. If you can show that there's no performance degradation, I'd be interested in accepting the patch :)

**Comment by SX91** [comment]
It always extends buffer (so basically it's incrementally converts lazy bytestring to strict).

**Comment by SX91** [comment]
That approach is slower. Slightly, but there're no real benefits in slowing things down.

**Comment by elliottt** [comment]
Ah, dang. Well thanks for the investigation!
