### ISSUE TITLE
How to handle a change in representation with generic serialization?

### ISSUE THREAD

**Issue by abailly** [GaloisInc/cereal#65]
I am using `Generic` support in cereal to serialize my data types to binary format, which works fine. However I am now facing a thorny issue related to migration: I have old representations of my data types that need to be deserialised to a type with a (slightly) different structure. Note that I am storing the known version along with the serialized form of the data, which allows me to know which transformation to apply when deserializing (assuming a monotonically increasing version number).

I previously used to serialise to/from JSON using aeson, which makes it easy to handle this migration issue: First deserialise to a JSON value then apply the needed changes to reconstruct a value consistent with your the new structure of the type. 

However, I am stuck applying the same strategy with cereal because it is not clear to me what's the underlying bytestring representation of generic types. I understand that it should read enough bytes to represent my sum of product type then dispatch on the read number according to which constructors and walk the generic tree. Am I correct? Any idea on how to do this in the simplest possible way?

**Comment by abailly** [comment]
I tried to do something very simple and it seems to work:

* Read a single byte as a tag for my constructor
* Dispatch on this tag and recursively call `getXXX` depending on the version  I am working with

**Comment by elliottt** [comment]
You might be interested in the [safecopy](http://hackage.haskell.org/package/safecopy) library, which adds version information to the serialized data.

Do you mind if we close this ticket, as it seems like you were able to resolve your problem?

**Comment by abailly** [comment]
Thanks for reaching out @elliottt !
Actually, I am still struggling with this issue, but on a different level... http://stackoverflow.com/questions/42179682/how-to-handle-data-structure-migration-in-a-compositional-way-in-haskell safecopy is nice but does not really seems to be what I want: It needs to keep old versions' definitions around which does not seem a good way to go if you plan to handle tens or hundreds of schema changes.

At least, I have a simple working solution :)
