### ISSUE TITLE
Use `fromDistinctAscList` to `get` Map, Set, IntSet and IntMap

### ISSUE THREAD

**Issue by sjakobi** [GaloisInc/cereal#66]
Or am I missing a reason why this wouldn't work?

For benefits, compare https://github.com/fpco/store/pull/101.

**Comment by elliottt** [comment]
Not checking the precondition that `fromDistinctAscList` requires is a security risk. For some context, here's the original discussion in pull request https://github.com/GaloisInc/cereal/pull/20.

**Comment by sjakobi** [comment]
Ah, thanks for the pointer. That's very interesting!
