### ISSUE TITLE
put :: Putter Integer quadratic(?) memory use

### ISSUE THREAD

**Issue by sliedes** [GaloisInc/cereal#68]
Using cereal 0.5.4.0, putting an Integer causes memory use to explode in an overlinear fashion to the size (in bits) of the Integer. Here's a table of memory usages (in bytes) with the following program:

```
weighEncode :: Weigh ()
weighEncode =
  do forM_ ([0, 1000..10000] ++ [20000, 30000..100000] ++ [200000, 300000..1000000]) $
       \x -> func (show x) weighExponent x
       where weighExponent n = BS.length $ encode ((2^n) :: Integer)

memProf :: IO ()
memProf = mainWith weighEncode
```

```
Case         Allocated     GCs
0                4,688       0
1000            58,016       0
2000           125,600       0
3000           208,720       0
4000           307,408       0
5000           421,744       0
6000           551,776       1
7000           697,224       1
8000           858,472       1
9000         1,035,264       2
10000        1,227,728       2
20000        4,011,416      10
30000        8,357,160      19
40000       14,305,160      30
50000       21,776,120      44
60000       30,815,032      61
70000       41,414,856      80
80000       53,575,848     104
90000       67,299,584     129
100000      82,582,672     158
200000     321,357,784     602
300000     716,433,208   1,331
400000   1,267,721,672   2,341
500000   1,975,251,800   3,622
600000   2,839,080,936   5,150
700000   3,859,106,568   6,944
800000   5,035,376,032   9,034
900000   6,367,966,256  11,378
1000000  7,856,746,304  13,884
```

A 1e6-bit number in GHC fits in a few megabytes at most; there cannot be much reason why encoding it should take 8 gigabytes.

**Comment by TomMD** [comment]
Does making `unroll` strict in `i` help?

**Comment by TomMD** [comment]
Curiously, are you also observing some unexpected performance or memory use?  I ask because it is important to keep in mind the number of bytes allocated does not correlate with the maximum heap residency.

**Comment by sliedes** [comment]
Memory use, in the very least. Trying to encode a 4e6-bit Integer exhausts my 32 GiB RAM in seconds.

**Comment by sliedes** [comment]
Also, decoding seems to also have a similar memory usage issue.

**Comment by TomMD** [comment]
I can't reproduce any maximum residency issues with decode.  Feel free to test the above pull request.
