### ISSUE TITLE
Support for Decimal128

### ISSUE THREAD

**Issue by sadraskol** [GaloisInc/cereal#77]
Hello,

Is there any plan on supporting [decimal128](https://en.wikipedia.org/wiki/Decimal128_floating-point_format) ? I don't have the knowledge in binary formats to implement it myself, but I'm ready to help in other ways if need be.

Thanks

**Comment by TomMD** [comment]
There are no active development plans. cereal is mature and in a maintenance state. If you'd like to implement decimal128 then I'd be happy to test it out and give comments.
