### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by MaxGabriel** [GaloisInc/cereal#82]
Hi, if it's no trouble, do you mind cutting a new release? The latest version's tests don't pass since https://github.com/GaloisInc/cereal/commit/00ea19fc1221e3859a18b4efcf106ac2f6247ef1 is unreleased.

It's not a huge deal, I can work around it, it's just that default builds using Nix fail due to the latest test suite not passing, which seems like a needless issue for people to run into.

**Comment by glguy** [comment]
Released

**Comment by MaxGabriel** [comment]
Thanks @glguy
