### ISSUE TITLE
Question about Generic serialiazation/deserialization, Not a bug (a priori)

### ISSUE THREAD

**Issue by teto** [GaloisInc/cereal#88]
There was no README so I am not sure where to ask for help (please redirect me if it's not correct)

I have these long datatypes (that I hope to generate from <linux>/include/uapi/linux/inet_diag.h)
```
data IDiagExtension =  DiagTcpInfo {
  tcpi_state :: Word8,
  tcpi_ca_state :: Word8,
  tcpi_retransmits :: Word8,
  tcpi_probes :: Word8,
  tcpi_backoff :: Word8,
  tcpi_options :: Word8,
  tcpi_wscales :: Word8,
  -- tcpi_snd_wscale : 4, tcpi_rcv_wscale : 4 :: Word8,

  tcpi_rto :: Word32,
  tcpi_ato :: Word32,
  tcpi_snd_mss :: Word32,
  tcpi_rcv_mss :: Word32,

  tcpi_unacked :: Word32,
  tcpi_sacked :: Word32,
  tcpi_lost :: Word32,
  tcpi_retrans :: Word32,
  tcpi_fackets :: Word32,

  -- Time
  tcpi_last_data_sent :: Word32,
  -- Not remembered, sorr
  tcpi_last_ack_sent :: Word32,
  tcpi_last_data_recv :: Word32,
  tcpi_last_ack_recv :: Word32,

   -- Metric
  tcpi_pmtu :: Word32,
  tcpi_rcv_ssthresh :: Word32,
  tcpi_rtt :: Word32,
  tcpi_rttvar :: Word32,
  tcpi_snd_ssthresh :: Word32,
  tcpi_snd_cwnd :: Word32,
  tcpi_advmss :: Word32,
  tcpi_reordering :: Word32,
  tcpi_rcv_rtt :: Word32,
  tcpi_rcv_space :: Word32,
  tcpi_total_retrans :: Word32
} | Meminfo {
  idiag_rmem :: Word32
, idiag_wmem :: Word32
, idiag_fmem :: Word32
, idiag_tmem :: Word32
} | TcpVegasInfo {
  tcpInfoVegasEnabled :: Word32
  , tcpInfoRttCount :: Word32
  , tcpInfoRtt :: Word32
  , tcpInfoMinrtt :: Word32
} | CongInfo String deriving (Show, Generic, Serialize)
```
that "derive" `Serialize` with the hope that I don't have to write the serialization/deserialization manually (since I send/receive messages over netlink-hs https://github.com/Ongy/netlink-hs/issues/9 that uses cereal)

My code to deserialize, the key (e.g., InetDiagCong) indicate which constructor to use:  (e.g., CongInfo)
```
loadExtension :: Int -> ByteString -> Maybe IDiagExtension
loadExtension key value =
  case toEnum key of
    InetDiagCong -> case decode value of
                        Right x -> Just $ x
                        Left err -> error $ "DiagCong error " ++ err

    -- _ -> case runGet (getGet 42) value of
    _ -> case decode value of
                        Right x -> Just x
                        -- Left err -> error $ "fourre-tout error " ++ err
                        Left err -> Nothing

```
but it generates a few errors such as 
```
        daemon: DiagCong error too few bytes
        From:       demandInput
    
        CallStack (from HasCallStack):
        error, called at IDiag.hs:449:37 in main:IDiag
    
    or
    
        "Unknown encoding for constructor"
    
    or
        Error too few bytes
```

Though I've made huge progress in learning haskell, I am still a beginner so I might miss sthg obvious. The code is here https://github.com/teto/netlink_pm/blob/c5d2254f4c87503b31e8b1f00859203bd86ad2f8/hs/IDiag.hs#L413 . Like when calling `decode` can cereal select the appropriate IDiagExtension Constructor ?
When I had the "Unknown encoding for constructor", happens for the `InetDiagCong` case, I expect it to call the `CongInfo` constructor. The string contains only ASCII characters (Word8 characters), any idea how to fix that ?

**Comment by glguy** [comment]
cereal will handle picking the correct constructor, and the serializer/deserializer pair. You don't need to encode that information yourself. If you're using the derived instances you should only try to deserialize values that the derived instance has serialized.

**Comment by teto** [comment]
Thanks for the fast answer !
in the present case, I deserialize a bytestring sent over netlink (i.e., not serialized by cereal). Can cereal Generics handle this scenario. Otherwise does that mean cereal's serialize adds metadata when serializing Generics ? 
For instance, `Meminfo`'s constructor looks easy to automate: serialize (write 4 Word32), deserialize (read 4 Word32),  though byteorder may be a concern.

**Comment by elliottt** [comment]
`cereal` uses its own serialization format, so deriving the `Serialize` instance will not allow you to decode a format other than the `cereal` format. If you're interested in some examples of using `cereal` to parse network formats, [hans](https://github.com/galoisinc/hans) uses `cereal` extensively.  For example, here is the module responsible for parsing/rendering TCP packets: https://github.com/GaloisInc/HaNS/blob/master/src/Hans/Tcp/Packet.hs.

**Comment by teto** [comment]
I see so what I had in mind (automatic serialization/deserialization to/from network) what not achievable in the first place :'(
Thanks for the helpful pointer to hans, this is how I've written my code so far but it's bording to write these serialization routines https://github.com/teto/netlink_pm/blob/c5d2254f4c87503b31e8b1f00859203bd86ad2f8/hs/IDiag.hs#L202 so I was hoping to automate a bit (especially when looking at DiagTcpInfo in my first post).
Thanks to you both for the prompt answers.
