### ISSUE TITLE
doc issue

### ISSUE THREAD

**Issue by blinaa** [GaloisInc/cereal#94]
https://hackage.haskell.org/package/cereal-0.5.8.1/docs/Data-Serialize-Get.html#v:runGetState
It says that the function returns the number of consumed bytes, but it's not

**Comment by blinaa** [comment]
Also,  i want to know how to get that number

**Comment by elliottt** [comment]
Yep, looks like the docs aren't up to date. You can use `bytesRead` and return that as part of your result to figure out how much was read total.
